.\" 
.\" virtual paper manual page.
.\" Author:
.\"   Jeff Tickle (jeff at jeff tickle dot com)
.\"
.de Sp
.if t .sp .5v
.if n .sp
..
.TH Virtual Paper "Virtual Paper 0.0.1"
.SH NAME
virtualpaper \- Virtual Paper for your Tablet PC
.SH SYNOPSIS
.PP
.B virtualpaper
.SH DESCRIPTION
\fIvirtualpaper\fP allows you to hand-write on a sheet of virtual paper.
.SH SEE ALSO
.BR mono(1)


