// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace MonoDevelop.Database.Designer {
    
    
    public partial class UniqueConstraintEditorWidget {
        
        private Gtk.HBox hbox;
        
        private Gtk.ScrolledWindow windowUnique;
        
        private Gtk.TreeView listUnique;
        
        private Gtk.VButtonBox vbuttonbox;
        
        private Gtk.Button buttonAdd;
        
        private Gtk.Button buttonRemove;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize();
            // Widget MonoDevelop.Database.Designer.UniqueConstraintEditorWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "MonoDevelop.Database.Designer.UniqueConstraintEditorWidget";
            // Container child MonoDevelop.Database.Designer.UniqueConstraintEditorWidget.Gtk.Container+ContainerChild
            this.hbox = new Gtk.HBox();
            this.hbox.Name = "hbox";
            this.hbox.Spacing = 6;
            // Container child hbox.Gtk.Box+BoxChild
            this.windowUnique = new Gtk.ScrolledWindow();
            this.windowUnique.CanFocus = true;
            this.windowUnique.Name = "windowUnique";
            this.windowUnique.VscrollbarPolicy = ((Gtk.PolicyType)(1));
            this.windowUnique.HscrollbarPolicy = ((Gtk.PolicyType)(1));
            this.windowUnique.ShadowType = ((Gtk.ShadowType)(1));
            // Container child windowUnique.Gtk.Container+ContainerChild
            this.listUnique = new Gtk.TreeView();
            this.listUnique.CanFocus = true;
            this.listUnique.Name = "listUnique";
            this.listUnique.HeadersClickable = true;
            this.windowUnique.Add(this.listUnique);
            this.hbox.Add(this.windowUnique);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox[this.windowUnique]));
            w2.Position = 0;
            // Container child hbox.Gtk.Box+BoxChild
            this.vbuttonbox = new Gtk.VButtonBox();
            this.vbuttonbox.Name = "vbuttonbox";
            this.vbuttonbox.Spacing = 6;
            this.vbuttonbox.LayoutStyle = ((Gtk.ButtonBoxStyle)(3));
            // Container child vbuttonbox.Gtk.ButtonBox+ButtonBoxChild
            this.buttonAdd = new Gtk.Button();
            this.buttonAdd.CanFocus = true;
            this.buttonAdd.Name = "buttonAdd";
            this.buttonAdd.UseStock = true;
            this.buttonAdd.UseUnderline = true;
            this.buttonAdd.Label = "gtk-add";
            this.vbuttonbox.Add(this.buttonAdd);
            Gtk.ButtonBox.ButtonBoxChild w3 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox[this.buttonAdd]));
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbuttonbox.Gtk.ButtonBox+ButtonBoxChild
            this.buttonRemove = new Gtk.Button();
            this.buttonRemove.Sensitive = false;
            this.buttonRemove.CanFocus = true;
            this.buttonRemove.Name = "buttonRemove";
            this.buttonRemove.UseStock = true;
            this.buttonRemove.UseUnderline = true;
            this.buttonRemove.Label = "gtk-remove";
            this.vbuttonbox.Add(this.buttonRemove);
            Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox[this.buttonRemove]));
            w4.Position = 1;
            w4.Expand = false;
            w4.Fill = false;
            this.hbox.Add(this.vbuttonbox);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox[this.vbuttonbox]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            this.Add(this.hbox);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.buttonAdd.Clicked += new System.EventHandler(this.AddClicked);
            this.buttonRemove.Clicked += new System.EventHandler(this.RemoveClicked);
        }
    }
}
