//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace umbraco.cms.presentation {
    
    public partial class theTask {
        protected System.Web.UI.HtmlControls.HtmlForm dataForm;
        protected System.Web.UI.HtmlControls.HtmlInputText nodeID;
        protected System.Web.UI.HtmlControls.HtmlInputText nodeType;
        protected System.Web.UI.HtmlControls.HtmlInputText task;
        protected System.Web.UI.HtmlControls.HtmlInputText parameterName;
        protected System.Web.UI.HtmlControls.HtmlInputText parameterNumber;
        protected System.Web.UI.WebControls.Label debug;
    }
}
