//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace umbraco.dialogs {
    
    public partial class AssignDomain {
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected System.Web.UI.WebControls.Literal FeedBackMessage;
        protected System.Web.UI.WebControls.RequiredFieldValidator DomainValidator;
        protected System.Web.UI.WebControls.TextBox DomainName;
        protected System.Web.UI.WebControls.RequiredFieldValidator LanguageValidator;
        protected System.Web.UI.WebControls.DropDownList Languages;
        protected System.Web.UI.WebControls.Button ok;
        protected System.Web.UI.HtmlControls.HtmlTable Table1;
        protected System.Web.UI.WebControls.Literal allDomains;
    }
}
