//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace umbraco.dialogs {
    
    public partial class publish {
        protected System.Web.UI.HtmlControls.HtmlForm Form1;
        protected System.Web.UI.WebControls.Literal FeedBackMessage;
        protected System.Web.UI.WebControls.PlaceHolder progressBar;
        protected System.Web.UI.WebControls.Panel TheForm;
        protected System.Web.UI.HtmlControls.HtmlTable Table1;
        protected System.Web.UI.WebControls.CheckBox PublishAll;
        protected System.Web.UI.WebControls.Button ok;
    }
}
