#!/bin/sh
export MONODIR=`echo \`which mono\` | sed 's|bin/mono||'`
export MONO_PATH=.:${MONODIR}/lib/mono/1.0/:${MONODIR}/lib/mono/mono-debugger/:${MONO_PATH}

mono --debug mdb-gui.exe --listen 28004 -run TestApp.exe
