//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace umbraco.controls.GenericProperties {
    
    public partial class GenericProperty {
        protected System.Web.UI.WebControls.ImageButton DeleteButton;
        protected System.Web.UI.WebControls.Literal Header;
        protected System.Web.UI.WebControls.ImageButton DeleteButton2;
        protected System.Web.UI.WebControls.Literal FullHeader;
        protected System.Web.UI.HtmlControls.HtmlTable form;
        protected System.Web.UI.WebControls.TextBox tbName;
        protected System.Web.UI.WebControls.TextBox tbAlias;
        protected System.Web.UI.WebControls.DropDownList ddlTypes;
        protected System.Web.UI.WebControls.DropDownList ddlTab;
        protected System.Web.UI.WebControls.CheckBox checkMandatory;
        protected System.Web.UI.WebControls.TextBox tbValidation;
        protected System.Web.UI.WebControls.TextBox tbDescription;
    }
}
